/**
 * Mock Data — Dữ liệu mẫu để test giao diện khi Firestore chưa có dữ liệu.
 * Hình ảnh sử dụng placeholder từ picsum.photos.
 */

export const mockHeroSlides = [
  {
    id: "slide-1",
    image: "https://picsum.photos/id/1015/1600/800",
    title: "Khám phá Việt Nam",
    subtitle: "Hành trình đáng nhớ qua những miền đất tuyệt vời",
    ctaText: "Xem Tour Ngay",
    ctaLink: "/tours",
  },
  {
    id: "slide-2",
    image: "https://picsum.photos/id/1018/1600/800",
    title: "Du lịch Đông Nam Á",
    subtitle: "Thái Lan, Campuchia, Lào — trọn gói giá tốt",
    ctaText: "Khám Phá Ngay",
    ctaLink: "/tours",
  },
  {
    id: "slide-3",
    image: "https://picsum.photos/id/1043/1600/800",
    title: "Tour Trăng Mật Lãng Mạn",
    subtitle: "Dành riêng cho hai bạn — giá ưu đãi đặc biệt",
    ctaText: "Đặt Ngay",
    ctaLink: "/tours",
  },
];

export const mockFeaturedDestinations = [
  { id: "loc-1", name: "Đà Nẵng", slug: "da-nang", featuredImage: "https://picsum.photos/id/1010/600/750", tourCount: 45 },
  { id: "loc-2", name: "Hội An", slug: "hoi-an", featuredImage: "https://picsum.photos/id/1016/600/750", tourCount: 32 },
  { id: "loc-3", name: "Hà Nội", slug: "ha-noi", featuredImage: "https://picsum.photos/id/1021/600/750", tourCount: 58 },
  { id: "loc-4", name: "Sapa", slug: "sapa", featuredImage: "https://picsum.photos/id/1036/600/750", tourCount: 28 },
  { id: "loc-5", name: "Nha Trang", slug: "nha-trang", featuredImage: "https://picsum.photos/id/1044/600/750", tourCount: 39 },
  { id: "loc-6", name: "Phú Quốc", slug: "phu-quoc", featuredImage: "https://picsum.photos/id/1051/600/750", tourCount: 41 },
  { id: "loc-7", name: "Đà Lạt", slug: "da-lat", featuredImage: "https://picsum.photos/id/1047/600/750", tourCount: 35 },
  { id: "loc-8", name: "Huế", slug: "hue", featuredImage: "https://picsum.photos/id/1055/600/750", tourCount: 22 },
];

export const mockFeaturedTours = [
  {
    id: "tour-1",
    slug: "tour-da-nang-hoi-an-3n2d",
    name: "Tour Đà Nẵng - Hội An 3N2Đ",
    featuredImage: "https://picsum.photos/id/1010/800/600",
    pricing: { adultPrice: 2990000 },
    discountPercent: 15,
    ratingAverage: 4.8,
    reviewCount: 124,
    duration: "3 ngày 2 đêm",
    locationName: "Đà Nẵng",
  },
  {
    id: "tour-2",
    slug: "tour-sapa-fansipan-2n2d",
    name: "Tour Sapa - Fansipan 2N2Đ",
    featuredImage: "https://picsum.photos/id/1036/800/600",
    pricing: { adultPrice: 3500000 },
    discountPercent: 10,
    ratingAverage: 4.7,
    reviewCount: 89,
    duration: "2 ngày 2 đêm",
    locationName: "Sapa",
  },
  {
    id: "tour-3",
    slug: "tour-nha-trang-dao-4n3d",
    name: "Tour Nha Trang Đảo 4N3Đ",
    featuredImage: "https://picsum.photos/id/1044/800/600",
    pricing: { adultPrice: 4200000 },
    discountPercent: 20,
    ratingAverage: 4.6,
    reviewCount: 67,
    duration: "4 ngày 3 đêm",
    locationName: "Nha Trang",
  },
  {
    id: "tour-4",
    slug: "tour-phu-quoc-resort-3n2d",
    name: "Nghỉ Dưỡng Phú Quốc 3N2Đ",
    featuredImage: "https://picsum.photos/id/1051/800/600",
    pricing: { adultPrice: 5800000 },
    ratingAverage: 4.9,
    reviewCount: 156,
    duration: "3 ngày 2 đêm",
    locationName: "Phú Quốc",
  },
  {
    id: "tour-5",
    slug: "tour-ha-noi-ha-long-2n1d",
    name: "Tour Hà Nội - Hạ Long 2N1Đ",
    featuredImage: "https://picsum.photos/id/1021/800/600",
    pricing: { adultPrice: 1800000 },
    discountPercent: 5,
    ratingAverage: 4.5,
    reviewCount: 201,
    duration: "2 ngày 1 đêm",
    locationName: "Hà Nội",
  },
  {
    id: "tour-6",
    slug: "tour-hue-da-nang-4n3d",
    name: "Tour Huế - Đà Nẵng 4N3Đ",
    featuredImage: "https://picsum.photos/id/1055/800/600",
    pricing: { adultPrice: 4800000 },
    discountPercent: 12,
    ratingAverage: 4.7,
    reviewCount: 73,
    duration: "4 ngày 3 đêm",
    locationName: "Huế",
  },
  {
    id: "tour-7",
    slug: "tour-da-lat-cao-nguyen-3n2d",
    name: "Tour Đà Lạt Cao Nguyên 3N2Đ",
    featuredImage: "https://picsum.photos/id/1047/800/600",
    pricing: { adultPrice: 2600000 },
    ratingAverage: 4.6,
    reviewCount: 98,
    duration: "3 ngày 2 đêm",
    locationName: "Đà Lạt",
  },
  {
    id: "tour-8",
    slug: "tour-mien-tay-song-nuoc-2n1d",
    name: "Tour Miền Tây Sông Nước 2N1Đ",
    featuredImage: "https://picsum.photos/id/1015/800/600",
    pricing: { adultPrice: 1500000 },
    discountPercent: 8,
    ratingAverage: 4.4,
    reviewCount: 55,
    duration: "2 ngày 1 đêm",
    locationName: "Miền Tây",
  },
];

export const mockBestActivities = [
  {
    id: "act-1",
    slug: "lan-bien-nha-trang",
    name: "Lặn Biển Ngắm San Hô Nha Trang",
    featuredImage: "https://picsum.photos/id/1043/800/600",
    pricing: { adultPrice: 750000 },
    discountPercent: 10,
    ratingAverage: 4.8,
    reviewCount: 256,
    duration: "Nửa ngày",
    locationName: "Nha Trang",
  },
  {
    id: "act-2",
    slug: "trekking-fansipan",
    name: "Trekking Chinh Phục Fansipan",
    featuredImage: "https://picsum.photos/id/1036/800/600",
    pricing: { adultPrice: 1800000 },
    ratingAverage: 4.9,
    reviewCount: 178,
    duration: "2 ngày 1 đêm",
    locationName: "Sapa",
  },
  {
    id: "act-3",
    slug: "chao-luon-hoi-an",
    name: "Chèo Thuyền Rổ Làng Chài Hội An",
    featuredImage: "https://picsum.photos/id/1016/800/600",
    pricing: { adultPrice: 350000 },
    discountPercent: 15,
    ratingAverage: 4.7,
    reviewCount: 412,
    duration: "2-3 tiếng",
    locationName: "Hội An",
  },
  {
    id: "act-4",
    slug: "canyoning-da-lat",
    name: "Canyoning Đà Lạt — Vượt Thác",
    featuredImage: "https://picsum.photos/id/1042/800/600",
    pricing: { adultPrice: 850000 },
    ratingAverage: 4.7,
    reviewCount: 145,
    duration: "1 ngày",
    locationName: "Đà Lạt",
  },
  {
    id: "act-5",
    slug: "cau-ca-phu-quoc",
    name: "Câu Cá & Lặn Ngắm San Hô Phú Quốc",
    featuredImage: "https://picsum.photos/id/1051/800/600",
    pricing: { adultPrice: 650000 },
    discountPercent: 5,
    ratingAverage: 4.6,
    reviewCount: 198,
    duration: "1 ngày",
    locationName: "Phú Quốc",
  },
  {
    id: "act-6",
    slug: "basket-boat-sapa",
    name: "Khám Phá Bản Làng Dân Tộc Sapa",
    featuredImage: "https://picsum.photos/id/1037/800/600",
    pricing: { adultPrice: 550000 },
    ratingAverage: 4.5,
    reviewCount: 167,
    duration: "1 ngày",
    locationName: "Sapa",
  },
];

export const mockTestimonials = [
  {
    id: "rev-1",
    userName: "Nguyễn Minh Anh",
    userAvatar: "https://picsum.photos/id/64/100/100",
    rating: 5,
    title: "Chuyến đi tuyệt vời",
    content: "Tour Đà Nẵng - Hội An 3N2Đ thật sự rất đáng giá. Hướng dẫn viên nhiệt tình, khách sạn sạch đẹp, đồ ăn ngon. Gia đình mình rất hài lòng và sẽ quay lại với 9Trip!",
  },
  {
    id: "rev-2",
    userName: "Trần Văn Hoàng",
    rating: 5,
    title: "Đặt tour nhanh chóng, giá tốt",
    content: "Mình đặt tour Phú Quốc cho gia đình 4 người. Giá rẻ hơn so với các bên khác khoảng 15%. Dịch vụ chuyên nghiệp, không phát sinh chi phí. Sẽ giới thiệu cho bạn bè.",
  },
  {
    id: "rev-3",
    userName: "Lê Thị Hương",
    userAvatar: "https://picsum.photos/id/65/100/100",
    rating: 4,
    content: "Tour Sapa - Fansipan 2N2Đ thời tiết đẹp, đoàn vui vẻ. Mỗi tội xe hơi chật nhưng bù lại hướng dẫn viên rất có tâm. Tổng thể chấm 4 sao.",
  },
  {
    id: "rev-4",
    userName: "Phạm Quốc Bảo",
    rating: 5,
    title: "Dịch vụ xuất sắc",
    content: "Từ khâu tư vấn đến khi kết thúc tour, mọi thứ đều rất trơn tru. Nhân viên gọi điện xác nhận trước tour 2 ngày, nhắc nhở lịch trình rất chu đáo. Cảm ơn 9Trip!",
  },
  {
    id: "rev-5",
    userName: "Đặng Mỹ Linh",
    userAvatar: "https://picsum.photos/id/91/100/100",
    rating: 5,
    title: "Trăng mật lãng mạn",
    content: "Vợ chồng mình đặt tour trăng mật Nha Trang 4N3Đ. Khách sạn view biển đẹp, lãng mạn. Cảm ơn 9Trip đã tạo bất ngờ với bánh kem chúc mừng!",
  },
  {
    id: "rev-6",
    userName: "Bùi Thanh Tùng",
    rating: 4,
    content: "Tour Huế - Đà Nẵng tổ chức tốt, hướng dẫn viên am hiểu lịch sử. Điểm trừ là thời gian ở Huế hơi ngắn, nên kéo dài thêm nửa ngày. Còn lại mọi thứ OK.",
  },
];

export const mockLatestNews = [
  {
    id: "news-1",
    slug: "kinh-nghiem-du-lich-da-nang-tu-tuc",
    title: "Kinh Nghiệm Du Lịch Đà Nẵng Tự Túc Chi Tiết Nhất 2026",
    excerpt: "Tổng hợp kinh nghiệm du lịch Đà Nẵng: thời điểm lý tưởng, phương tiện di chuyển, khách sạn, địa điểm tham quan và ẩm thực không thể bỏ lỡ.",
    thumbnail: "https://picsum.photos/id/1010/800/500",
    publishedAt: "2026-04-20",
    author: "9Trip Travel Guide",
  },
  {
    id: "news-2",
    slug: "top-10-resort-phu-quoc-sang-chanh",
    title: "Top 10 Resort Phú Quốc Sang Chảnh Cho Kỳ Nghỉ Hoàn Hảo",
    excerpt: "Khám phá những resort đẳng cấp nhất tại đảo Ngọc Phú Quốc, từ phong cách nghỉ dưỡng đến tiện ích 5 sao cho chuyến đi của bạn.",
    thumbnail: "https://picsum.photos/id/1051/800/500",
    publishedAt: "2026-04-18",
    author: "9Trip Travel Guide",
  },
  {
    id: "news-3",
    slug: "le-hoi-hoa-anh-dao-da-lat-2026",
    title: "Lễ Hội Hoa Anh Đào Đà Lạt 2026 — Đừng Bỏ Lỡ",
    excerpt: "Mùa hoa anh đào Đà Lạt đẹp nhất trong năm, cùng những hoạt động văn hóa đặc sắc. Đặt tour ngay để không bỏ lỡ mùa lễ hội.",
    thumbnail: "https://picsum.photos/id/1047/800/500",
    publishedAt: "2026-04-15",
    author: "9Trip Travel Guide",
  },
];

export const mockSearchSuggestions = {
  destinations: ["Đà Nẵng", "Hội An", "Hà Nội", "Sapa", "Nha Trang", "Phú Quốc", "Đà Lạt", "Huế"],
  tourTypes: ["Tour Trọn Gói", "Tour Ghép Đoàn", "Tour Riêng", "Tour Nghỉ Dưỡng", "Tour Mạo Hiểm"],
};